env:
  browser: true
  es6: true
  node: true
  mocha: true

# recommended settings are listed in following URL
# https://eslint.org/docs/rules/
extends: eslint:recommended

parser: babel-eslint

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

plugins:
  - flowtype
  - react

rules:
  # Stylistic Issues are processed by prettier

  # Possible Errors
  # https://eslint.org/docs/rules/#possible-errors
  no-console: [warn, { allow: [warn, error] }]

  # Best Practices
  # http://eslint.org/docs/rules/#best-practices
  array-callback-return: error
  block-scoped-var: error
  complexity: [error, 8]
  consistent-return: error
  curly: error
  default-case: error
  dot-location: [error, property]
  dot-notation: [error, { allowKeywords: true }]
  eqeqeq: error
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: [error, { allowElseIf: true }]
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: [error, {enforceConst: true}]
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-redeclare: error
  no-restricted-properties: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  vars-on-top: error
  wrap-iife: error
  yoda: [error, never, {exceptRange: true}]

  # Variables
  # https://eslint.org/docs/rules/#variables
  init-declarations: error
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars: error
  no-use-before-define: error

  # EcmaScript6
  # https://eslint.org/docs/rules/#ecmascript-6
  arrow-body-style: [error, as-needed]
  arrow-parens: [error, as-needed]
  constructor-super: error
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-imports: error
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  sort-imports: off
  symbol-description: error

  # flowtype
  # https://github.com/gajus/eslint-plugin-flowtype
  flowtype/define-flow-type: error
  flowtype/use-flow-type: error

  # React.js
  # https://github.com/gajus/eslint-plugin-flowtype
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
