Current = "0.0.1"

[[Files]]
  Path = "README.md"
  Prefix = "dic v"
  Postfix = ""
  IsNumber = false

[[Files]]
  Path = "package.json"
  Prefix = "\"version\": \""
  Postfix = ""
  IsNumber = false
